export const ServiceTypes = [
	"Counselor",
	"Health Coach",
	"Life Coach",
	"Medication Coach",
	"Naturopathic Physician",
	"Psychotherapist",
	"Substance Abuse Counselor",
	"SUD Coach",
	"Therapist",
	"Trauma Specialist",
	"Counselor1",
	"Health Coach1",
	"Life Coach1",
]

export const SpecialistTypes = [
	"Counselor",
	"Health Coach",
	"Life Coach",
	"Medication Coach",
	"Naturopathic Physician",
	"Psychotherapist",
	"Substance Abuse Counselor",
	"SUD Coach",
	"Therapist",
	"Trauma Specialist",
	"Counselor1",
	"Health Coach1",
	"Life Coach1",
]

export const allFeelings = [
	"Stress",
	"Trauma",
	"Lack of Focus",
	"Anxiety",
	"Addictions",
	"Depression",
	"Burnout",
	"Eating Disorders",
	"Insecurity",
	"Abuse",
	"Sexuality Issues",
	"OCD",
	"Spiritual Suffering",
	"Perinatal Depression",
	"Personality Disorders",
	"Mood Disorders",
	"PTSD",
	"Grief",
	"Nutrition",
	"Movement",
	"Identity",
]